{% set name = "spyder-remote-server" %}
{% set version = "0.0.25" %}
{% set hash = "ec6e8e20efe608a82b75b291073ef6d9454d2b46e211225618fd9b9874206d34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - spyder-remote-server = spyder_remote_server.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - click
    - daemoniker
    - jinja2
    - python >={{ python_min }}
    - pyzmq
    - zeroconf

test:
  requires:
    - python {{ python_min }}
  commands:
    - spyder-remote-server --help
  imports:
    - spyder_remote_server

about:
  home: https://github.com/Semi-ATE/spyder-remote/tree/master/spyder-remote-server
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder remote server to connect to Spyder kernels via zeroconf
  description: |
    Spyder remote server to connect to Spyder kernels via zeroconf.
  doc_url: https://semi-ate.github.io/spyder-remote/
  dev_url: https://github.com/Semi-ATE/spyder-remote/

extra:
  recipe-maintainers:
    - goanpeca
    - nerohmot
